name: supasync_cli
description: A CLI tool to streamline local development with Supabase and PowerSync.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Documentation
# DCLI - https://dcli.onepub.dev/

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  collection: ^1.19.0
  dart_console: ^4.1.0
  dcli: ^4.0.3
  docker2: ^4.5.0
  dotenv: ^4.2.0
  embed_annotation: ^1.2.1
  path: ^1.9.0
  process_run: ^1.0.0+1

dev_dependencies:
  build_runner: ^2.4.11
  embed: ^1.4.0
  lints: ^4.0.0
  test: ^1.24.0

executables:
  supasync: supasync
