name: supasync_cli
description: A CLI tool to streamline local development with Supabase and PowerSync.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  supasync: supasync_cli
